import { DomainError } from '@moi/trading-core';

/**
 * The single global lock order of the ledger.
 *
 * The order is (rank of table in this array, then row key ascending as a
 * string), and `createLockOrderGuard` refuses any acquisition that would go
 * backwards in it — so an inconsistent order is a test failure in this
 * repository rather than a deadlock in production.
 *
 * What that buys is stated precisely, because a total order on its own does
 * not buy deadlock freedom. PostgreSQL makes a transaction wait in exactly two
 * ways that any statement in these repositories can produce, and both have to
 * be ordered:
 *
 *   1. **A row lock.** A set of transactions that always acquires row locks in
 *      one total order, and never *strengthens* a lock it already holds, can
 *      never form a wait cycle: a transaction only ever waits for a resource
 *      ranked above everything it holds, so a cycle would need a resource
 *      strictly above itself. A strengthening breaks that argument — two
 *      transactions each holding `for key share` on one row and each then
 *      asking for `for update` on it wait for one another while both are
 *      perfectly in order — so `acquireLock` refuses it. A transaction has to
 *      take the strongest lock it will need on its first touch of a row.
 *   2. **A transaction id, through a unique index.** An `insert` (or an
 *      `update` that writes an indexed column) that collides with another
 *      transaction's uncommitted index entry waits for that whole transaction,
 *      not for a row. That wait is invisible to a row-lock order, so every
 *      unique index a repository statement can collide on is either declared
 *      through `claimUniqueKey` — which places the claim in this same order, at
 *      the rank of the table that owns it — or classified in
 *      `LEDGER_UNIQUE_INDEXES` with the reason it needs no claim. The suite
 *      reads the unique indexes out of PostgreSQL's own catalog and fails if any
 *      index is unclassified, so a new index cannot be added without an answer.
 *
 * The two kinds are not taken in the order they read in. Inside one statement
 * PostgreSQL writes the index entries while the statement runs and checks the
 * foreign keys in AFTER ROW triggers that fire when it ends, so an `insert` that
 * both claims an index and pins a parent takes **the claim first**. That is not
 * something a ranking can repair: the claim of a statement cannot be ranked
 * below a parent the same statement pins afterwards, whichever rank either one
 * is given. So the rule for such a statement is stronger than ordering — every
 * foreign-key parent it pins has to be **held already**, which makes the pin
 * acquire nothing and therefore unable to wait. The claim is declared in the
 * position PostgreSQL takes it, the pin is declared after it, and the guard
 * refuses the pin unless the row is already held: a bare `outbox.append` or
 * `idempotency.begin` on an unpinned session is inexpressible rather than a
 * deadlock waiting for two concurrent callers. The suite measures that physical
 * order against PostgreSQL itself rather than asserting it.
 *
 * The residue is named rather than hidden: the seven indexes keyed on a per-row
 * identity — a uuid generated by a repository, or supplied once by its caller —
 * are classified `FRESH_IDENTITY`, and a collision
 * on one of them means a caller reused an identity. That is a caller defect
 * rather than contention, it cannot be ordered (the two transactions are writing
 * what they believe is the same row), and the deadlock it can produce is
 * absorbed by the retry — which the suite pins, with exactly one effect.
 *
 * The ranks are ordered from the most coarse-grained row to the most
 * fine-grained: a mutation starts by pinning the session that owns the ledger,
 * claims the idempotency key that identifies the request, then its balances,
 * then the grouping row, then individual orders, then the reservation each
 * order holds, and last the outbox event it publishes. Every mutation therefore enters the order at the top and moves
 * down it.
 *
 * Every lock counts, not only an explicit `select … for update`. Three kinds of
 * row lock reach this order:
 *
 *   * `for update` on a read, the strongest and the only one that is visible in
 *     the SQL text;
 *   * `for no key update`, which PostgreSQL takes implicitly on every row an
 *     `update` touches without changing a key column;
 *   * `for key share`, which every foreign-key check takes on the parent row an
 *     `insert` (or a key-changing `update`) references.
 *
 * The third kind is the one that is easy to miss and the one that produced real
 * deadlocks before it was declared: `insert into orders` pins the session row
 * and the OCO group row, `insert into outbox_events` and the idempotency writes
 * pin the session row, and `insert into reservations` pins the session and the
 * order. A transaction that took an order lock first and only then inserted was
 * acquiring a rank-0 lock after a rank-5 lock without saying so.
 *
 * `audit_events` is absent because it references nothing: it is append-only and
 * carries no foreign key, so it locks nothing. `account_sequences` is absent
 * because nothing ever locks a row in it: sequences are allocated only while
 * the owning session is held for update, so their computed unique key cannot
 * contend, and an insert locks its parents, not its own invisible new row.
 * `reservations` is ranked below `orders` because releasing a reservation
 * (cancellation, terminal fill) updates its row after the order it belongs to
 * has been locked, and above `outbox_events` because the release is published
 * last. A future `update` against `account_sequences` cannot be declared,
 * because `acquireLock` refuses a table with no rank, so the omission fails
 * loudly rather than silently.
 */
export const LEDGER_LOCK_ORDER = Object.freeze([
  'anonymous_sessions',
  'idempotency_requests',
  'wallets',
  'positions',
  'oco_groups',
  'orders',
  'reservations',
  'outbox_events',
] as const);

export type LockTable = (typeof LEDGER_LOCK_ORDER)[number];

/**
 * Tables of immutable reference data, deliberately outside the lock order.
 *
 * `markets` is read by foreign keys on `orders`, `positions` and
 * `reservations`, so an insert does take a `for key share` lock on a market
 * row. It needs no rank because no statement in this application ever locks a
 * market row in a mode that conflicts with `for key share`: the rows are
 * written once by the migration and never updated. Shared locks never wait on
 * one another, so no wait edge can exist here, and a lock that cannot wait
 * cannot be part of a cycle. The suite measures this rather than assuming it —
 * every repository method is checked for a stronger-than-shared lock on a
 * reference row.
 */
export const LEDGER_REFERENCE_TABLES = Object.freeze(['markets'] as const);

/**
 * Why each unique index of the ledger cannot put this application in a wait
 * cycle.
 *
 *   * `ORDERED_CLAIM` — two concurrent requests can legitimately compute this
 *     key, so the statement that writes it declares the claim through
 *     `claimUniqueKey` and the claim takes its place in `LEDGER_LOCK_ORDER`.
 *     The declaration goes where PostgreSQL takes it — before the statement's
 *     foreign-key pins, not after them — which is why every parent of a
 *     claiming statement has to be held before it runs.
 *   * `FRESH_IDENTITY` — the key is a uuid generated or supplied once per row.
 *     Two concurrent requests never compute the same one; a collision means a
 *     caller reused an identity, which is a defect in the caller. The resulting
 *     deadlock is retried like any other 40P01.
 *   * `UNWRITTEN` — no repository statement inserts into the table, and no
 *     repository `update` writes any column of the index, so no index entry is
 *     ever added and no conflict is reachable. `markets` and `fills` are here
 *     too: a repository never writes either, but an insert reaches both as a
 *     foreign-key parent, so leaving them out would have narrowed the claim
 *     below what it says.
 *   * `SESSION_SERIALIZED` — the key is computed while the owning session row
 *     is held for update, so two transactions cannot compute it concurrently.
 *
 * The suite reads `pg_index` and asserts that this map covers exactly the unique
 * indexes the schema defines on every table a repository statement touches,
 * foreign-key parents included. The partitions of `audit_events` are outside
 * that set by construction — a partition's unique index enforces the parent's
 * key rather than a key of its own — and the suite measures that rather than
 * asserting it.
 */
export type UniqueIndexArbiter =
  | 'ORDERED_CLAIM'
  | 'FRESH_IDENTITY'
  | 'SESSION_SERIALIZED'
  | 'UNWRITTEN';

export interface UniqueIndexClassification {
  readonly table: string;
  readonly arbiter: UniqueIndexArbiter;
}

export const LEDGER_UNIQUE_INDEXES: Readonly<
  Record<string, UniqueIndexClassification>
> = Object.freeze({
  idempotency_requests_session_id_idempotency_key_key: {
    table: 'idempotency_requests',
    arbiter: 'ORDERED_CLAIM',
  },
  orders_one_oco_winner_per_group: {
    table: 'orders',
    arbiter: 'ORDERED_CLAIM',
  },
  outbox_events_session_id_stream_sequence_key: {
    table: 'outbox_events',
    arbiter: 'ORDERED_CLAIM',
  },
  audit_events_pkey: { table: 'audit_events', arbiter: 'FRESH_IDENTITY' },
  idempotency_requests_pkey: {
    table: 'idempotency_requests',
    arbiter: 'FRESH_IDENTITY',
  },
  orders_pkey: { table: 'orders', arbiter: 'FRESH_IDENTITY' },
  outbox_events_event_id_key: {
    table: 'outbox_events',
    arbiter: 'FRESH_IDENTITY',
  },
  outbox_events_pkey: { table: 'outbox_events', arbiter: 'FRESH_IDENTITY' },
  reservations_pkey: { table: 'reservations', arbiter: 'FRESH_IDENTITY' },
  fills_pkey: { table: 'fills', arbiter: 'UNWRITTEN' },
  // The fill cursor. Its value comes from a bigserial default, so two writers
  // never compute the same one; like `fills_pkey` it is UNWRITTEN because no
  // repository statement inserts a fill — the runtime's raw-SQL fill path does.
  fills_sequence_idx: { table: 'fills', arbiter: 'UNWRITTEN' },
  // Pairs (id, session_id) so `fills` can carry a foreign key to both and the
  // denormalised owner cannot diverge from the order's. Orders are inserted
  // with a fresh uuid, so this key collides only if a caller reuses an id.
  orders_id_session_key: { table: 'orders', arbiter: 'FRESH_IDENTITY' },
  markets_pkey: { table: 'markets', arbiter: 'UNWRITTEN' },
  account_sequences_pkey: {
    table: 'account_sequences',
    arbiter: 'FRESH_IDENTITY',
  },
  account_sequences_session_id_account_sequence_key: {
    table: 'account_sequences',
    arbiter: 'SESSION_SERIALIZED',
  },
  anonymous_sessions_pkey: {
    table: 'anonymous_sessions',
    arbiter: 'UNWRITTEN',
  },
  anonymous_sessions_token_hash_key: {
    table: 'anonymous_sessions',
    arbiter: 'UNWRITTEN',
  },
  oco_groups_pkey: { table: 'oco_groups', arbiter: 'UNWRITTEN' },
  positions_pkey: { table: 'positions', arbiter: 'UNWRITTEN' },
  positions_session_id_market_code_symbol_key: {
    table: 'positions',
    arbiter: 'UNWRITTEN',
  },
  wallets_pkey: { table: 'wallets', arbiter: 'UNWRITTEN' },
  wallets_session_id_currency_key: {
    table: 'wallets',
    arbiter: 'UNWRITTEN',
  },
});

/** The unique indexes a statement declares through `claimUniqueKey`. */
export type ClaimedUniqueIndex =
  | 'idempotency_requests_session_id_idempotency_key_key'
  | 'orders_one_oco_winner_per_group'
  | 'outbox_events_session_id_stream_sequence_key';

/**
 * The claim key of the one-winner-per-OCO-group index.
 *
 * The claim shares rank 5 with the `orders` rows themselves, and it has to sort
 * *after* every one of them: PostgreSQL takes the row lock first and inserts the
 * index entry second, so a transaction that has claimed the winner slot must not
 * then wait for an order row. Order ids are uuids, so their keys only ever
 * contain `0-9`, `a-f` and `-`; `'o'` sorts above all of those. The suite pins
 * that rather than trusting it.
 *
 * What that means for a caller that resolves an OCO pair — cancelling the losing
 * leg while naming the winner — is that it has to lock *both* legs at `UPDATE`,
 * in ascending id order, before it updates either: the first winner-naming
 * update claims the slot, and after that no order row may be locked at all. The
 * refusal is loud rather than silent, but it is easier to read here than to
 * discover from the message.
 */
export function ocoWinnerClaimKey(ocoGroupId: string): string {
  return `oco-winner:${ocoGroupId}`;
}

const KEY_PART_ESCAPE = /[\\:]/g;

/**
 * Renders a multi-column natural key as one lock key.
 *
 * The parts are joined with `:` after escaping `:` and `\` inside them, so two
 * different rows can never render to one key: without the escape,
 * `('a:b', 'c')` and `('a', 'b:c')` would collide and the guard would treat two
 * rows as one, skipping an ordering check.
 */
export function compositeLockKey(...parts: readonly string[]): string {
  return parts
    .map((part) => part.replace(KEY_PART_ESCAPE, (char) => `\\${char}`))
    .join(':');
}

const SEQUENCE_KEY_WIDTH = 20;

/**
 * Renders a sequence number as a lock key that sorts numerically.
 *
 * Lock keys are compared as strings, so `'10'` would sort below `'2'` and two
 * appends in ascending sequence order would look like an inversion. A bigint
 * needs at most 19 digits, so zero-padding to 20 makes the string order the
 * numeric order. A negative sequence has no such rendering and is refused
 * rather than silently mis-ordered.
 */
export function sequenceLockKey(value: bigint): string {
  if (value < 0n) {
    throw new DomainError(
      'INVARIANT_VIOLATION',
      `a lock key cannot be built from the negative sequence ${value}`,
    );
  }
  return value.toString().padStart(SEQUENCE_KEY_WIDTH, '0');
}

/**
 * How strongly a row is held, in PostgreSQL's own row-lock order.
 *
 * Strength matters to the ordering discipline because a *strengthening* of a
 * lock already held is a fresh acquisition that can block: a transaction
 * holding `for key share` on a session row (from a foreign-key check) and then
 * asking for `for update` on it waits for every other holder of the shared
 * lock. Two transactions running that identical sequence deadlock while both
 * obey the order, so the strengthening is refused outright rather than ordered.
 */
export type LockStrength = 'KEY_SHARE' | 'NO_KEY_UPDATE' | 'UPDATE';

const STRENGTH_RANK: Readonly<Record<LockStrength, number>> = Object.freeze({
  KEY_SHARE: 0,
  NO_KEY_UPDATE: 1,
  UPDATE: 2,
});

export interface LockTarget {
  readonly table: LockTable;
  /**
   * The row's natural key rendered as a string. It has to be the natural key
   * rather than the surrogate id, because a lock must be ordered before the row
   * has been read — and because two statements that touch one row have to
   * produce the same key whichever identity they address it by.
   */
  readonly key: string;
  readonly strength: LockStrength;
}

/**
 * A unique-index entry the next statement will insert, and therefore a wait on
 * whichever transaction holds a conflicting uncommitted entry.
 */
export interface UniqueKeyClaim {
  readonly table: LockTable;
  /** The index's own key, rendered the way `LockTarget.key` is. */
  readonly key: string;
  readonly index: ClaimedUniqueIndex;
}

/** The lock-order discipline of one open transaction. */
export interface LockOrderGuard {
  /**
   * Declares the row lock the next statement will take. Throws
   * INVARIANT_VIOLATION when it would violate `LEDGER_LOCK_ORDER`, and when it
   * would strengthen a lock this transaction already holds.
   */
  acquireLock(target: LockTarget): void;
  /**
   * Declares the unique-index entry the next statement will insert. Throws
   * INVARIANT_VIOLATION when the claim would go backwards in
   * `LEDGER_LOCK_ORDER`, and when the index is not one this order claims.
   */
  claimUniqueKey(claim: UniqueKeyClaim): void;
}

function lockRank(table: string): number {
  return (LEDGER_LOCK_ORDER as readonly string[]).indexOf(table);
}

interface OrderCursor {
  readonly rank: number;
  readonly key: string;
  /**
   * Which channel the resource came from. It changes only the diagnostic: a row
   * lock that goes backwards past a *claim* is not an inversion the caller can
   * fix by reordering, because PostgreSQL takes the claim first, so the message
   * names the rule that does fix it.
   */
  readonly kind: 'row' | 'claim';
  readonly description: string;
}

/**
 * Creates the guard for one transaction.
 *
 * `onLock` observes each row lock that really happens — a re-declaration of
 * something already held at the same or greater strength acquires nothing and is
 * not reported. `onClaim` observes each unique-key claim. They are separate
 * channels because they measure different things: a row lock is observable from
 * another backend, and a claim on a row that does not exist yet is not.
 */
export function createLockOrderGuard(
  onLock?: (target: LockTarget) => void,
  onClaim?: (claim: UniqueKeyClaim) => void,
): LockOrderGuard {
  const held = new Map<string, LockStrength>();
  const claimed = new Set<string>();
  let last: OrderCursor | undefined;

  const rankOf = (table: string): number => {
    const rank = lockRank(table);
    if (rank < 0) {
      throw new DomainError(
        'INVARIANT_VIOLATION',
        `${table} has no rank in the ledger lock order`,
      );
    }
    return rank;
  };

  const refuseIfBackwards = (cursor: OrderCursor): void => {
    if (
      last !== undefined &&
      (cursor.rank < last.rank ||
        (cursor.rank === last.rank && cursor.key < last.key))
    ) {
      const rule =
        last.kind === 'claim' && cursor.kind === 'row'
          ? ` — a statement that writes a claimed index entry pins its foreign-key parents after writing it, so ${cursor.description} has to be held before the statement runs`
          : '';
      throw new DomainError(
        'INVARIANT_VIOLATION',
        `lock order violation: ${cursor.description} must not be locked after ${last.description}${rule}`,
      );
    }
    last = cursor;
  };

  return {
    acquireLock(target: LockTarget): void {
      const rank = rankOf(target.table);
      // `held` and `claimed` are separate namespaces, so a row identity and a
      // claim identity that render alike never collide.
      const identity = `${rank}:${target.key}`;
      const alreadyHeld = held.get(identity);
      if (alreadyHeld !== undefined) {
        // Re-locking a row this transaction already holds at least this
        // strongly acquires nothing, so it cannot extend a wait cycle and needs
        // no ordering.
        if (STRENGTH_RANK[alreadyHeld] >= STRENGTH_RANK[target.strength]) {
          return;
        }
        // A strengthening does acquire something, and no ordering can make it
        // safe: two transactions running this identical sequence wait for one
        // another. The strongest lock has to come first.
        throw new DomainError(
          'INVARIANT_VIOLATION',
          `lock order violation: ${target.table} (${target.key}) is already held ${alreadyHeld} and may not be strengthened to ${target.strength} — a transaction has to take the strongest lock it needs on its first touch of a row`,
        );
      }

      refuseIfBackwards({
        rank,
        key: target.key,
        kind: 'row',
        description: `${target.table} (${target.key})`,
      });
      held.set(identity, target.strength);
      onLock?.(target);
    },

    claimUniqueKey(claim: UniqueKeyClaim): void {
      const rank = rankOf(claim.table);
      const classification = LEDGER_UNIQUE_INDEXES[claim.index];
      if (
        classification === undefined ||
        classification.arbiter !== 'ORDERED_CLAIM' ||
        classification.table !== claim.table
      ) {
        throw new DomainError(
          'INVARIANT_VIOLATION',
          `${claim.index} is not a claimed unique index of ${claim.table}`,
        );
      }

      const identity = `${rank}:${claim.key}`;
      if (claimed.has(identity)) {
        return;
      }
      refuseIfBackwards({
        rank,
        key: claim.key,
        kind: 'claim',
        description: `the ${claim.index} entry (${claim.key})`,
      });
      claimed.add(identity);
      onClaim?.(claim);
    },
  };
}
